# Generated by Django 6.0.5 on 2026-05-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mfname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wfco', models.CharField(db_index=True, max_length=10, verbose_name='성분코드')),
                ('fname', models.CharField(blank=True, max_length=200, verbose_name='성분명')),
                ('igrno1', models.CharField(blank=True, max_length=20, verbose_name='상호작용성분코드1')),
                ('igrno2', models.CharField(blank=True, max_length=20, verbose_name='상호작용성분코드2')),
                ('igrno3', models.CharField(blank=True, max_length=20, verbose_name='상호작용성분코드3')),
                ('igrno4', models.CharField(blank=True, max_length=20, verbose_name='상호작용성분코드4')),
            ],
            options={
                'verbose_name': '상호작용 성분코드 매핑',
                'verbose_name_plural': '상호작용 성분코드 매핑 목록',
                'ordering': ['wfco'],
            },
        ),
        migrations.CreateModel(
            name='Mintef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igrno_a', models.CharField(db_index=True, max_length=20, verbose_name='상호작용코드 A')),
                ('igrno_b', models.CharField(db_index=True, max_length=20, verbose_name='상호작용코드 B')),
                ('irisk', models.CharField(blank=True, max_length=20, verbose_name='위험도')),
                ('idesc', models.TextField(blank=True, verbose_name='상호작용 유형')),
                ('ireco', models.TextField(blank=True, verbose_name='대처 방법')),
            ],
            options={
                'verbose_name': '약품 상호작용',
                'verbose_name_plural': '약품 상호작용 목록',
                'ordering': ['igrno_a', 'igrno_b'],
            },
        ),
    ]
