# Generated by Django 6.0.5 on 2026-05-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htname', models.CharField(max_length=200, verbose_name='약품명')),
                ('ingred', models.CharField(max_length=500, verbose_name='성분명')),
                ('ee', models.TextField(blank=True, verbose_name='효능')),
                ('ud', models.TextField(blank=True, verbose_name='용량')),
                ('nb', models.TextField(blank=True, verbose_name='주의사항')),
                ('company', models.CharField(max_length=200, verbose_name='회사명')),
            ],
            options={
                'verbose_name': '의약정보',
                'verbose_name_plural': '의약정보 목록',
                'ordering': ['htname'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htname', models.CharField(max_length=200, verbose_name='약품명')),
                ('ingred', models.CharField(max_length=500, verbose_name='성분명')),
                ('company', models.CharField(max_length=200, verbose_name='회사명')),
            ],
            options={
                'verbose_name': '의약품',
                'verbose_name_plural': '의약품 목록',
                'ordering': ['htname'],
            },
        ),
    ]
