# Generated by Django 6.0.5 on 2026-05-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='wfco',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10, verbose_name='주성분코드'),
        ),
    ]
